### ISSUE TITLE
如何获得example的数据文件

### ISSUE THREAD

**Issue by YongcanZhou** [yijixiuxin/chanlun-pro#1]
如何获得example的数据文件，我可以跑代码，但是数据的获取需要麻烦学习一下，谢谢~

**Comment by yijixiuxin** [comment]
沪深历史行情使用的是：http://baostock.com/
期货行情使用的 ：https://github.com/shinnytech/tqsdk-python
数字货币用 各个交易所的 api 接口，或者 [ccxt](https://github.com/ccxt/ccxt)
